[package]
authors = ["Matt Vertescher <mvertescher@gmail.com>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "HAL for the STM32F7xx family of microcontrollers"
edition = "2018"
keywords = ["arm", "cortex-m", "stm32f7xx", "hal"]
license = "MIT OR Apache-2.0"
name = "stm32f7xx-hal"
repository = "https://github.com/mvertescher/stm32f7xx-hal"
version = "0.1.0"

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.7"
nb = "0.1.1"
stm32f7 = "0.5.0"

[dependencies.bare-metal]
version = "0.2.4"
features = ["const-fn"]

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.2"

[dependencies.void]
default-features = false
version = "1.0.2"

[dev-dependencies]
panic-halt = "0.2.0"
panic-semihosting = "0.5.0"

[features]
default = ["stm32f746"]
doc = []
rt = ["stm32f7/rt"]
stm32f746 = ["stm32f7/stm32f7x6"]

[package.metadata.docs.rs]
features = ["stm32f746", "rt"]

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
